# ============================ Filebeat inputs =============================
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/dev/*.json.log

    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true

# ============================== Filebeat outputs ==============================
output.logstash:
  hosts: ["www.jhzlo.world:5044"]

# ========================== Processors ===============================
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# ============================== X-Pack Monitoring ===============================
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
  hosts: ["www.jhzlo.world:9200"]
