spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

  flyway:
    enabled: true
    baseline-version: 0
    locations:
      - classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: ${MANAGEMENT_BASE_PATH}
    jmx:
      exposure:
        exclude: "*"

  prometheus:
    metrics:
      export:
        enabled: true

cookie:
  secure: true
  same-site: None
  domain: .lettie.me
