spring:
  application:
    name: lettie

  profiles:
    active: local

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg [%X{requestId}]%n"

management:
  endpoints:
    web:
      exposure:
        include: health

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${OAUTH_REDIRECT_URI}
    client-name: kakao
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    scope: profile_nickname,profile_image
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH_REDIRECT_URI}
    client-name: Google
    authorization-uri: https://accounts.google.com/o/oauth2/auth
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
    scope: email,profile
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${OAUTH_REDIRECT_URI}
    client-name: naver
    authorization-uri: https://nid.naver.com/oauth2.0/authorize
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    state: ${NAVER_STATE}


jwt:
  client-secret: ${JWT_SECRET}
  expiration: 86400000
  issuer: yapp

llm:
  key: ${LLM_KEY}
  id: ${LLM_ID}
  service-name: ${LLM_SERVICE_NAME}
  base-url: ${LLM_BASE_URL}

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL}

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        timeout: 5000
        connectiontimeout: 5000
        writetimeout: 5000
        starttls:
          enable: true
