CREATE TABLE LETTER
(
    ID              BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID         BIGINT,
    TIME_CAPSULE_ID BIGINT,
    CONTENT         VARCHAR(255),
    FROMS           VARCHAR(255),
    CREATED_AT DATETIME(6)  NOT NULL,
    UPDATED_AT DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE LETTER_FILE
(
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    LETTER_ID  BIGINT,
    OBJECT_KEY VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME(6)  NOT NULL,
    UPDATED_AT DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID)
)
