-- Autogenerated: do not edit this file

CREATE TABLE batch_job_instance (
                                    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
                                    VERSION BIGINT,
                                    JOB_NAME VARCHAR(100) NOT NULL,
                                    JOB_KEY VARCHAR(32) NOT NULL,
                                    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB;

CREATE TABLE batch_job_execution (
                                     JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                     VERSION BIGINT,
                                     JOB_INSTANCE_ID BIGINT NOT NULL,
                                     CREATE_TIME DATETIME(6) NOT NULL,
                                     START_TIME DATETIME(6) DEFAULT NULL,
                                     END_TIME DATETIME(6) DEFAULT NULL,
                                     STATUS VARCHAR(10),
                                     EXIT_CODE VARCHAR(2500),
                                     EXIT_MESSAGE VARCHAR(2500),
                                     LAST_UPDATED DATETIME(6),
                                     constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
                                         references batch_job_instance(JOB_INSTANCE_ID)
) ENGINE=InnoDB;

CREATE TABLE batch_job_execution_params (
                                            JOB_EXECUTION_ID BIGINT NOT NULL,
                                            PARAMETER_NAME VARCHAR(100) NOT NULL,
                                            PARAMETER_TYPE VARCHAR(100) NOT NULL,
                                            PARAMETER_VALUE VARCHAR(2500),
                                            IDENTIFYING CHAR(1) NOT NULL,
                                            constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
                                                references batch_job_execution(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE batch_step_execution (
                                      STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                      VERSION BIGINT NOT NULL,
                                      STEP_NAME VARCHAR(100) NOT NULL,
                                      JOB_EXECUTION_ID BIGINT NOT NULL,
                                      CREATE_TIME DATETIME(6) NOT NULL,
                                      START_TIME DATETIME(6) DEFAULT NULL,
                                      END_TIME DATETIME(6) DEFAULT NULL,
                                      STATUS VARCHAR(10),
                                      COMMIT_COUNT BIGINT,
                                      READ_COUNT BIGINT,
                                      FILTER_COUNT BIGINT,
                                      WRITE_COUNT BIGINT,
                                      READ_SKIP_COUNT BIGINT,
                                      WRITE_SKIP_COUNT BIGINT,
                                      PROCESS_SKIP_COUNT BIGINT,
                                      ROLLBACK_COUNT BIGINT,
                                      EXIT_CODE VARCHAR(2500),
                                      EXIT_MESSAGE VARCHAR(2500),
                                      LAST_UPDATED DATETIME(6),
                                      constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
                                          references batch_job_execution(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE batch_step_execution_context (
                                              STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                              SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                              SERIALIZED_CONTEXT TEXT,
                                              constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
                                                  references batch_step_execution(STEP_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE batch_job_execution_context (
                                             JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                             SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                             SERIALIZED_CONTEXT TEXT,
                                             constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
                                                 references batch_job_execution(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE batch_step_execution_seq (
                                          ID BIGINT NOT NULL,
                                          UNIQUE_KEY CHAR(1) NOT NULL,
                                          constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO batch_step_execution_seq (ID, UNIQUE_KEY)
SELECT * FROM (SELECT 0 as ID, '0' as UNIQUE_KEY) as tmp
WHERE NOT EXISTS (SELECT * FROM batch_step_execution_seq);

CREATE TABLE batch_job_execution_seq (
                                         ID BIGINT NOT NULL,
                                         UNIQUE_KEY CHAR(1) NOT NULL,
                                         constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO batch_job_execution_seq (ID, UNIQUE_KEY)
SELECT * FROM (SELECT 0 as ID, '0' as UNIQUE_KEY) as tmp
WHERE NOT EXISTS (SELECT * FROM batch_job_execution_seq);

CREATE TABLE batch_job_seq (
                               ID BIGINT NOT NULL,
                               UNIQUE_KEY CHAR(1) NOT NULL,
                               constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT INTO batch_job_seq (ID, UNIQUE_KEY)
SELECT * FROM (SELECT 0 as ID, '0' as UNIQUE_KEY) as tmp
WHERE NOT EXISTS (SELECT * FROM batch_job_seq);
