name: YAPP Server CI-CD Workflow - DEV

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      reason:
        description: "Deployment reason (optional)"
        required: false
        default: "manual deploy"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build
        run: |
          docker build . \
          --build-arg SPRING_PROFILE=dev \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:dev

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:dev

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and trigger switch
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:dev

            echo "Starting blue-green switch..."
            bash /home/ec2-user/scripts/switch-blue-green.sh

            echo "Cleaning unused images..."
            docker image prune -f
